version: "3.9"

services:
  mysql:
    container_name: mysql_local
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul
